### ISSUE TITLE
Can't upload photo from web but work perfectly fine in https request

### ISSUE THREAD

**Issue by HaiCheViet** [IBM/powerai-vision-object-detection#61]
![image](https://user-images.githubusercontent.com/37202591/67026037-3ec06b00-f131-11e9-8094-577e1ca23768.png)
The web api return as like that and don't display the image and prediction on web

Tks in advance

**Comment by nirandiw** [comment]
Any idea how to resolve this?

**Comment by nirandiw** [comment]
I found a solution to this problem via stack overflow. Since the response is zipped the `console.log(body)` prints binary. In the response enable `gzip: true` and it will return the json string. You might want to integrate it to the code path. 

app.js --> app.post()--> request.post() include gzip: true as an option.

**Comment by horeaporutiu** [comment]
Thank you @HaiCheViet and @nirandiw this is now fixed with https://github.com/IBM/powerai-vision-object-detection/pull/67
